# INFO: choose your seed just below!
my_seed = 0
include("src/project.jl")
include("src/packages.jl")
include("src/constants.jl")
include("src/download.jl")
include("src/checksum.jl")
include("src/load.jl")
include("src/header.jl")
include("src/subdivide.jl")
include("src/format.jl")
include("src/exclude.jl")
include("src/indexing.jl")
include("src/cleaning.jl")
include("src/seed.jl")
include("src/select.jl")
include("src/concat.jl")
include("src/dcci.jl")
include("src/processing.jl")
include("src/result.jl")
