# INFO: This script must be run from the project's root directory.
root = pwd()
include(joinpath(root, "src/activate.jl"))
include(joinpath(root, "src/packages.jl"))
include(joinpath(root, "src/project.jl"))
include(joinpath(root, "src/test.jl"))
include(joinpath(root, "src/seed.jl"))
include(joinpath(root, "src/constants.jl"))
include(joinpath(root, "src/download.jl"))
include(joinpath(root, "src/checksum.jl"))
include(joinpath(root, "src/load.jl"))
include(joinpath(root, "src/header.jl"))
include(joinpath(root, "src/subdivide.jl"))
include(joinpath(root, "src/format.jl"))
include(joinpath(root, "src/exclude.jl"))
include(joinpath(root, "src/indexing.jl"))
include(joinpath(root, "src/cleaning.jl"))
include(joinpath(root, "src/select.jl"))
include(joinpath(root, "src/concat.jl"))
include(joinpath(root, "src/dcci.jl"))
include(joinpath(root, "src/processing.jl"))
include(joinpath(root, "src/result.jl"))
